services:
  app:
    image: paidem/avm:latest
    ports:
      - "5000:5000"
    volumes:
      - /media:/media
      - /media/avm/thumbnails:/app/static/thumbnails
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Vilnius
      - ADMIN_PASSWORD=action