services:
  # nginx is optional, but it uses less resources when streaming video than python app
  nginx:
    image: nginx:alpine
    container_name: media-streaming-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # volume name which has your media
      - nfs_footage:/media:ro
      # mount thumbnails directory so that nginx can serve them more effectively
      - nfs_thumbnails:/thumbnails:ro
    ports:
      - "5000:80"
    restart: unless-stopped
    environment:
      - TZ=Europe/Vilnius
  app:
    image: paidem/avm:latest
    volumes:
      # volume name which has your media
      - nfs_footage:/media:ro
      # mount thumbnails directory so that nginx can serve them more effectively
      - nfs_thumbnails:/thumbnails:ro
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Vilnius
      - REDIS_HOST=redis
      - ADMIN_PASSWORD=action
      - PRIVATE_FOLDERS=Personal,Own,OnlyForMyEyes
      - FILTERED_FILES=avm,.DS_Store,.Thumbs.db,Thumbs.db,.Trashes,.Spotlight-V100,.fseventsd,.Trashes,@eaDir,desktop.ini,thumbs.db,#snapshot,#recycle,thumbnails,redis_data,resize.log
      - HIDDEN_EXTENSIONS=source,srt,dng,log

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
  nfs_footage:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.10.90,rw
      device: ":/volume2/footage"
  # mount thumbnails directory so that nginx can serve them more effectively
  nfs_thumbnails:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.10.90,rw
      device: ":/volume2/footage/avm/thumbnails"