

volumes:
  nfs_footage:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.10.90,rw
      device: ":/volume2/footage"
  nfs_thumbnails:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.10.90,rw
      device: ":/volume2/footage/avm/thumbnails"

services:
  nginx:
    image: nginx:alpine
    container_name: media-streaming-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nfs_footage:/media:ro
      - nfs_thumbnails:/thumbnails:ro
    ports:
      - "5000:80"
    restart: unless-stopped
    environment:
      - TZ=Europe/Vilniuse
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - nfs_footage:/media
      - nfs_thumbnails:/app/static/thumbnails
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Vilnius
      - REDIS_HOST=redis
      - ADMIN_PASSWORD=action
      - PRIVATE_FOLDERS=Personal,Own,OnlyForMyEyes
      - FILTERED_FILES=avm,.DS_Store,.Thumbs.db,Thumbs.db,.Trashes,.Spotlight-V100,.fseventsd,.Trashes,@eaDir,desktop.ini,thumbs.db,#snapshot,#recycle,thumbnails,redis_data,resize.log
      - HIDDEN_EXTENSIONS=source,srt,dng,log
  redis:
    image: redis:alpine
    volumes:
      - ./redis_data:/data
    restart: unless-stopped
